name: Run LAMBench

on:
  workflow_dispatch:
    inputs:
      args:
        description: Arguments to pass to `lambench`
        required: false

jobs:
  run-lambench:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: pip

    - name: Install dependencies
      run: |
        pip install .[dflow]

    - name: Run LAMBench
      run: |
        lambench ${{ github.event.inputs.args }}
